---

root: true

plugins:
  - jest

parserOptions:
  ecmaVersion: latest

env:
  node: true
  jest: true
  browser: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
  - "plugin:playwright/playwright-test"

rules:
  no-console: 0
  import/extensions: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
      - req
      - reply
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
