name: Node CI

on:
  - push
  - pull_request

env:
  SESSION_KEY: ${{ secrets.SESSION_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - run: make setup
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test-coverage
          debug: true